version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      replicas: 1
    networks:
      - portainer_network

networks:
  portainer_network:
    driver: overlay

volumes:
  portainer_data:
