apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secret.data.POSTGRES_USER | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.data.POSTGRES_PASSWORD | b64enc | quote }}
  RABBIT_MQ_USER: {{ .Values.secret.data.RABBIT_MQ_USER | b64enc | quote }}
  RABBIT_MQ_PASSWORD: {{ .Values.secret.data.RABBIT_MQ_PASSWORD | b64enc | quote }}