Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
  
    config.vm.define "manager" do |manager|
      manager.vm.hostname = "manager"
      manager.vm.network "private_network", ip: "192.168.56.10"
      
      manager.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"  
        vb.cpus = 1         
      end
    end
  
    config.vm.define "server" do |server|
      server.vm.hostname = "server"
      server.vm.network "private_network", ip: "192.168.56.11"
      
      server.vm.network "forwarded_port", guest: 8500, host: 8500

      server.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"  
        vb.cpus = 1         
      end
    end
  
    config.vm.define "api" do |api|
      api.vm.hostname = "api"
      api.vm.network "private_network", ip: "192.168.56.12"
      
      api.vm.network "forwarded_port", guest: 8082, host: 8082

      api.vm.provider "virtualbox" do |vb|
        vb.memory = "3096"
        vb.cpus = 2         
      end
    end

    config.vm.define "db" do |db|
      db.vm.hostname = "db"
      db.vm.network "private_network", ip: "192.168.56.13"

      db.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
      end
    end
  end
