global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'email-and-telegram'

receivers:
  - name: 'email-and-telegram'
    email_configs:
      - to: 'max7kay@gmail.com'
        from: 'maksforplaymar@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'maksforplaymar@gmail.com'
        auth_password: '123321mM'
    telegram_configs:
      - send_resolved: true
        api_url: 'https://api.telegram.org'
        bot_token: '8054509717:AAHqXrikh_KHX6cViLKF3nmv74oWJdVI38k'
        chat_id: 889851983
        parse_mode: ''