version: '3.8'

services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    deploy:
      replicas: 1
    networks:
      - overlay_network

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    deploy:
      replicas: 1
    networks:
      - overlay_network

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
    ports:
      - 9093:9093

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
    depends_on:
      - loki
      - prometheus
    networks:
      - overlay_network

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    deploy:
      replicas: 1
    networks:
      - overlay_network

  blackbox_exporter:
    image: prom/blackbox-exporter
    ports:
      - "9115:9115"
    deploy:
      replicas: 1
    networks:
      - overlay_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
    networks:
      - overlay_network

  db_session:
    image: postgres:13
    deploy:
      replicas: 1
    container_name: session-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: users_db
    ports:
      - "5433:5432"
    volumes:
      - session-db-data:/var/lib/postgresql/data
    networks:
      - overlay_network

  db_hotel:
    image: postgres:13
    deploy:
      replicas: 1
    container_name: hotel-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: hotels_db
    ports:
      - "5434:5432"
    volumes:
      - hotel-db-data:/var/lib/postgresql/data
    networks:
      - overlay_network


  db_booking:
    image: postgres:13
    deploy:
      replicas: 1
    container_name: booking-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: reservations_db
    ports:
      - "5435:5432"
    volumes:
      - booking-db-data:/var/lib/postgresql/data
    networks:
      - overlay_network

  db_payment:
    image: postgres:13
    deploy:
      replicas: 1
    container_name: payment-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: payments_db
    ports:
      - "5436:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data
    networks:
      - overlay_network

  db_loyalty:
    image: postgres:13
    deploy:
      replicas: 1
    container_name: loyalty-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: balances_db
    ports:
      - "5437:5432"
    volumes:
      - loyalty-db-data:/var/lib/postgresql/data
    networks:
      - overlay_network

  db_report:
    image: postgres:13
    deploy:
      replicas: 1
    container_name: report-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: statistics_db
    ports:
      - "5438:5432"
    volumes:
      - report-db-data:/var/lib/postgresql/data
    networks:
      - overlay_network

  session:
    image: beyonder112/devops_7:session
    deploy:
      replicas: 1
    container_name: session-service
    depends_on:
      - db_session
    ports:
      - "8081:8081"
    environment:
      POSTGRES_HOST: db_session
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: users_db
    networks:
      - overlay_network

  hotel:
    image: beyonder112/devops_7:hotel
    deploy:
      replicas: 1
    container_name: hotel-service
    depends_on:
      - db_hotel
    environment:
      POSTGRES_HOST: db_hotel
      POSTGRES_PORT: 5432
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: hotels_db
    networks:
      - overlay_network

  booking:
    image: beyonder112/devops_7:booking
    deploy:
      replicas: 1
    container_name: booking-service
    depends_on:
      - db_booking
    ports:
      - "8083:8083"
    environment:
      POSTGRES_HOST: db_booking
      POSTGRES_PORT: 5432
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: reservations_db
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
      HOTEL_SERVICE_HOST: hotel
      HOTEL_SERVICE_PORT: 8082
      PAYMENT_SERVICE_HOST: payment
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty
      LOYALTY_SERVICE_PORT: 8085
    networks:
      - overlay_network

  loyalty:
    image: beyonder112/devops_7:loyalty
    deploy:
      replicas: 1
    container_name: loyalty-service
    depends_on:
      - db_loyalty
    environment:
      POSTGRES_HOST: db_loyalty
      POSTGRES_PORT: 5432
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: balances_db
    networks:
      - overlay_network

  report:
    image: beyonder112/devops_7:report
    deploy:
      replicas: 1
    container_name: report-service
    depends_on:
      - db_report
    ports:
      - "8086:8086"
    environment:
      POSTGRES_HOST: db_report
      POSTGRES_PORT: 5432
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: statistics_db
      RABBIT_MQ_HOST: rabbitmq
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_USER: guest
      RABBIT_MQ_PASSWORD: guest
      RABBIT_MQ_QUEUE_NAME: messagequeue
      RABBIT_MQ_EXCHANGE: messagequeue-exchange
    networks:
      - overlay_network

  payment:
    image: beyonder112/devops_7:payment
    deploy:
      replicas: 1
    container_name: payment-service
    depends_on:
      - db_payment
    environment:
      POSTGRES_HOST: db_payment
      POSTGRES_PORT: 5432
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD: 123321
      POSTGRES_DB: payments_db
    networks:
      - overlay_network

  gateway:
    image: beyonder112/devops_7:gateway
    deploy:
      replicas: 1
    container_name: gateway-service
    ports:
      - "8087:8087"
    depends_on:
      - session
      - hotel
      - booking
      - payment
      - loyalty
      - report
    environment:
      SESSION_SERVICE_HOST: session
      SESSION_SERVICE_PORT: 8081
      HOTEL_SERVICE_HOST: hotel
      HOTEL_SERVICE_PORT: 8082
      BOOKING_SERVICE_HOST: booking
      BOOKING_SERVICE_PORT: 8083
      PAYMENT_SERVICE_HOST: payment
      PAYMENT_SERVICE_PORT: 8084
      LOYALTY_SERVICE_HOST: loyalty
      LOYALTY_SERVICE_PORT: 8085
      REPORT_SERVICE_HOST: report
      REPORT_SERVICE_PORT: 8086
    logging:
      driver: "loki"
      options:
        loki-url: "http://192.168.56.10:3100/loki/api/v1/push"
    networks:
      - overlay_network

  rabbitmq:
    image: rabbitmq:3-management
    deploy:
      replicas: 1
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - overlay_network

networks:
  overlay_network:
    driver: overlay
    attachable: true

volumes:
  session-db-data:
  hotel-db-data:
  booking-db-data:
  payment-db-data:
  loyalty-db-data:
  report-db-data:


