Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  config.vm.define "manager01" do |manager|
    manager.vm.hostname = "manager01"
    manager.vm.network "private_network", ip: "192.168.56.10"

    manager.vm.network "forwarded_port", guest: 8087, host: 8087
    manager.vm.network "forwarded_port", guest: 8081, host: 8081
    manager.vm.network "forwarded_port", guest: 9000, host: 9000
    manager.vm.network "forwarded_port", guest: 9090, host: 9090 

    
    manager.vm.provider "virtualbox" do |vb|
      vb.memory = "6144"  
      vb.cpus = 4         
    end
  end

  config.vm.define "worker01" do |worker01|
    worker01.vm.hostname = "worker01"
    worker01.vm.network "private_network", ip: "192.168.56.11"
    
    worker01.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"  
      vb.cpus = 2         
    end
  end

  config.vm.define "worker02" do |worker02|
    worker02.vm.hostname = "worker02"
    worker02.vm.network "private_network", ip: "192.168.56.12"
    
    worker02.vm.provider "virtualbox" do |vb|
      vb.memory = "3072"
      vb.cpus = 2         
    end
  end
end
